development:
  # Configure available database sessions. (required)
  sessions:
    # Defines the default session. (required)
    default:
      database: veye_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: veye_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: veye_prod
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] ||= 'localhost' %>:<%= ENV['DB_PORT_27017_TCP_PORT'] ||= '27017' %>
        - <%= ENV['MONGO_RS_2_ADDR'] ||= 'localhost' %>:<%= ENV['MONGO_RS_2_PORT'] ||= '27017' %>
        - <%= ENV['MONGO_RS_3_ADDR'] ||= 'localhost' %>:<%= ENV['MONGO_RS_3_PORT'] ||= '27017' %>
      options:
        read: :secondary
        # write:
        #   w: :majority

enterprise:
  sessions:
    default:
      database: veye_enterprise
      hosts:
        - <%= ENV['DB_PORT_27017_TCP_ADDR'] ||= 'localhost' %>:<%= ENV['DB_PORT_27017_TCP_PORT'] ||= '27017' %>
        # - 192.168.118.133:27017
